name: Latest Tweets workflow
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from endi24
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "Updated readme with the latest endi24 data"
          #feed_list: "https://twitrss.me/twitter_search_to_rss/?term=endi24"
          feed_list: "https://www.spox.com/pub/rss/us-sport-nba.xml"
          #feed_list: "https://stackoverflow.com/feeds/user/4214976"
